# Rendering posed SMPL meshes with pyrender, then render SMPLpix predictions
#
# The scrtipt is heavily based on the SMPLify-x visualisation pipeline:
# https://github.com/vchoutas/smplify-x/blob/master/smplifyx/fit_single_frame.py

import os
import numpy as np
import pyrender
import trimesh
import argparse

os.environ['PYOPENGL_PLATFORM'] = 'egl'

def get_smplpix_arguments():

    parser = argparse.ArgumentParser(description='SMPLpix-renderer argument parser')
    parser.add_argument('--data_dir',
                        dest='data_dir',
                        help='SMPLpix data directory generated by the data preparation script',
                        default=None)

    args = parser.parse_args()

    return args


def render_mesh(mesh_trimesh, camera_center, camera_transl, focal_length, img_width, img_height):

    script_dir = os.path.dirname(os.path.realpath(__file__))
    vertex_colors = np.loadtxt(os.path.join(script_dir, 'smplx_verts_colors.txt'))
    mesh_new = trimesh.Trimesh(vertices=mesh_trimesh.vertices, faces=mesh_trimesh.faces, vertex_colors=vertex_colors)
    mesh_new.vertex_colors = vertex_colors
    print("mesh visual kind: %s" % mesh_new.visual.kind)

    mesh = pyrender.Mesh.from_trimesh(mesh_new, smooth=False, wireframe=False)

    scene = pyrender.Scene(bg_color=[0.0, 0.0, 0.0, 0.0],
                           ambient_light=(0.3, 0.3, 0.3))
    scene.add(mesh, 'mesh')

    camera_pose = np.eye(4)
    camera_pose[:3, 3] = camera_transl

    camera = pyrender.camera.IntrinsicsCamera(
        fx=focal_length, fy=focal_length,
        cx=camera_center[0], cy=camera_center[1])
    scene.add(camera, pose=camera_pose)

    light = pyrender.light.DirectionalLight()

    scene.add(light)
    r = pyrender.OffscreenRenderer(viewport_width=img_width,
                                   viewport_height=img_height,
                                   point_size=1.0)
    color, _ = r.render(scene, flags=pyrender.RenderFlags.RGBA)
    color = color.astype(np.float32) / 255.0

    output_img = color[:, :, 0:3]
    output_img = (output_img * 255).astype(np.uint8)

    return output_img